version: '3.9'

services:
  movie_review_api:
    container_name: movie_review_api
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env