# Generated by Django 5.0.2 on 2024-02-26 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Descrição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0, null=True, verbose_name='Nota')),
                ('year', models.DateField(verbose_name='Ano')),
                ('synopsis', models.TextField(verbose_name='Sinopse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='acted_in_movies', to='movie_review.artist', verbose_name='Ator')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='movie_review.artist', verbose_name='Diretor')),
                ('genders', models.ManyToManyField(to='movie_review.gender', verbose_name='Gênero')),
            ],
        ),
    ]
