# Generated by Django 5.0.2 on 2024-02-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='None', max_length=45),
        ),
    ]
