# Generated by Django 5.0.2 on 2024-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='None', max_length=45, unique=True),
        ),
    ]
